name: myapp
description: Ambientes Intelgentes project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.6
  connectivity: ^3.0.6
  dropdown_button2: ^1.2.2
  firebase_auth: ^3.3.10
  firebase_core: ^1.3.0
  firebase_storage: ^10.2.9
  outline_search_bar: ^2.3.0
  path_provider: ^2.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  random_avatar: ^0.0.5
  flutter:
    sdk: flutter
  
  loading_indicator: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.2
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/



