name: myapp
description: Ambientes Intelgentes project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.6
  connectivity: ^3.0.6
  firebase_auth: ^3.3.10
  firebase_core: ^1.3.0
  firebase_storage: ^10.2.9
  path_provider: ^2.0.2
  random_avatar: ^0.0.5
  flutter:
    sdk: flutter
  
  loading_indicator: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.2
  json_annotation: ^3.1.1
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.1
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true




